In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets, model_selection, svm, metrics

In [2]:
mnist_test = pd.read_csv("mnist_test.csv")
mnist_train = pd.read_csv("mnist_train.csv")

In [3]:
X_train = mnist_train.drop('label', axis=1).values
y_train = mnist_train['label'].values

In [4]:
X_test = mnist_test.drop('label', axis=1).values
y_test = mnist_test['label'].values

In [5]:
svm_classifier = svm.SVC(kernel='rbf', C=1)
svm_classifier.fit(X_train, y_train)

SVC(C=1)

In [6]:
y_pred = svm_classifier.predict(X_test)

In [7]:
X_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [8]:
y_train.reshape(len(y_train),1)

array([[5],
       [0],
       [4],
       ...,
       [5],
       [6],
       [8]], dtype=int64)

In [9]:
accuracy = metrics.accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.2f}")

Accuracy: 0.98


In [10]:
confusion_matrix = metrics.confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion_matrix)

Confusion Matrix:
[[ 973    0    1    0    0    2    1    1    2    0]
 [   0 1126    3    1    0    1    1    1    2    0]
 [   6    1 1006    2    1    0    2    7    6    1]
 [   0    0    2  995    0    2    0    5    5    1]
 [   0    0    5    0  961    0    3    0    2   11]
 [   2    0    0    9    0  871    4    1    4    1]
 [   6    2    0    0    2    3  944    0    1    0]
 [   0    6   11    1    1    0    0  996    2   11]
 [   3    0    2    6    3    2    2    3  950    3]
 [   3    4    1    7   10    2    1    7    4  970]]


In [26]:
pip install opencv-contrib-python

                                              0.0/44.8 MB ? eta -:--:--
                                              0.0/44.8 MB ? eta -:--:--
                                             0.0/44.8 MB 330.3 kB/s eta 0:02:16
                                             0.0/44.8 MB 660.6 kB/s eta 0:01:08
                                             0.0/44.8 MB 326.8 kB/s eta 0:02:17
                                             0.1/44.8 MB 363.1 kB/s eta 0:02:04
                                             0.1/44.8 MB 504.4 kB/s eta 0:01:29
                                             0.1/44.8 MB 566.5 kB/s eta 0:01:19
                                             0.2/44.8 MB 620.6 kB/s eta 0:01:12
                                             0.2/44.8 MB 593.2 kB/s eta 0:01:16
                                             0.2/44.8 MB 573.4 kB/s eta 0:01:18
                                             0.3/44.8 MB 561.1 kB/s eta 0:01:20
                                             0.3/44.8 MB

In [11]:
import numpy as np
import cv2  
from sklearn import svm

def preprocess_image(image_path):
    image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
    image = cv2.resize(image, (28, 28))
    feature_vector = image.flatten()
    return feature_vector

input_image_path = '0.jpg'
input_feature_vector = preprocess_image(input_image_path)

# Step 3: Prediction
predicted_label = svm_classifier.predict([input_feature_vector])

print(f"Predicted label: {predicted_label[0]}")


Predicted label: 2
